import type { Metadata } from "next";
import Providers from "./providers"; // 🔥 Import the separate client component
import "./globals.css";

export const metadata: Metadata = {
  title: "Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers> {/* ✅ Wrap children with SessionProvider */}
      </body>
    </html>
  );
}
